### ISSUE TITLE
Issue on login

### ISSUE THREAD

**Issue by JKetelaar** [lorenzh/fut-api#14]
Getting this error while trying to login:

```
Unable to login.
```

Debugging shows:

```
undefined
Error: Unknow response. Unable to login.
    at Request._callback (/Volumes/OTHER/FUT/FUT Bot/node_modules/fut-api/lib/login.js:293:28)
    at Request.self.callback (/Volumes/OTHER/FUT/FUT Bot/node_modules/request/request.js:198:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Volumes/OTHER/FUT/FUT Bot/node_modules/request/request.js:1035:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (/Volumes/OTHER/FUT/FUT Bot/node_modules/request/request.js:962:12)
    at emitNone (events.js:91:20)
    at Gunzip.emit (events.js:185:7)
Unable to login.
```

Debugging even further:

```
{ debug: '', string: '', code: '403', reason: '' }
```

Seems like a forbidden error, but no clue why.
I have tried both authentication using app and SMS, both providing the same error.

**Comment by JKetelaar** [comment]
NVM; Set platform incorrect
