### ISSUE TITLE
Error: Unable to get the 'EASW_ID'.

### ISSUE THREAD

**Issue by lBroth** [lorenzh/fut-api#20]
I get this error in login

Error: Unable to get the 'EASW_ID'. Unable to login.
at Request._callback (/var/nodejs/node_modules/fut-api/lib/login.js:205:75)
at Request.self.callback (/var/nodejs/node_modules/request/request.js:198:22)
at emitTwo (events.js:106:13)
at Request.emit (events.js:191:7)
at Request. (/var/nodejs/node_modules/request/request.js:1035:10)
at emitOne (events.js:101:20)
at Request.emit (events.js:188:7)
at Gunzip. (/var/nodejs/node_modules/request/request.js:962:12)
at emitNone (events.js:91:20)
at Gunzip.emit (events.js:185:7)

Do you have an idea to solve this?

**Comment by lBroth** [comment]
I think the EA sport web app server are down
