### ISSUE TITLE
Unable to login: Error: Unknow response

### ISSUE THREAD

**Issue by ghost** [lorenzh/fut-api#36]
Getting this error on trying to login:

Error: Unknow response. Unable to login.
    at Request._callback (/Users/ben/workspace/NodeWorkspace/fut-app/node_modules/fut-api/lib/login.js:157:28)
    at Request.self.callback (/Users/ben/workspace/NodeWorkspace/fut-app/node_modules/request/request.js:198:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/Users/ben/workspace/NodeWorkspace/fut-app/node_modules/request/request.js:1035:10)
    at emitOne (events.js:120:20)
    at Request.emit (events.js:210:7)
    at Gunzip.<anonymous> (/Users/ben/workspace/NodeWorkspace/fut-app/node_modules/request/request.js:962:12)
    at emitNone (events.js:110:20)
    at Gunzip.emit (events.js:207:7)

**Comment by manuelmarichal** [comment]
Take a look at this

https://github.com/lorenzh/fut-api/issues/35
