### ISSUE TITLE
Got issue at apiRequest.post

### ISSUE THREAD

**Issue by mfsdcool** [lorenzh/fut-api#7]
Looks like you have created a great work! I am new to this and try to run it in Nodejs. I can login successfully but for further functions it throw our .post undefined issue.

Maybe looks stupid but would like to seek your help.. Thanks a lot

xxx\fut-api\index.js:199
      loginResponse.apiRequest.post(url,
                              ^
TypeError: Cannot read property 'post' of undefined
    at sendRequest (xxx\node_modules\fut-api\index.js:199:31)
    at futApi.getCredits (xxx\node_modules\fut-api\index.js:7

**Comment by lorenzh** [comment]
could you give me an example? 

are you waiting for the login response?

**Comment by derSoerrn95** [comment]
`TypeError: Cannot call method 'post' of undefined
    at sendRequest (/var/www/html/FIFA/node_modules/fut-api/index.js:210:32)
    at futApi.search (/var/www/html/FIFA/node_modules/fut-api/index.js:102:7)
    at Object.tradeController.searchPlayer (/var/www/html/FIFA/controller/tradeController.js:17:23)
    at /var/www/html/FIFA/routes/control.js:114:25
    at Layer.handle [as handle_request] (/var/www/html/FIFA/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/html/FIFA/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/var/www/html/FIFA/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/www/html/FIFA/node_modules/express/lib/router/layer.js:95:5)
    at /var/www/html/FIFA/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/var/www/html/FIFA/node_modules/express/lib/router/index.js:330:12)`

it appears when u arn't logged in
